backend/BoxOffice/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static
from django.conf.urls import url,include
from home.views import ShowIndex, RegisterView, LoginView,SearchView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('myapi.urls')),
    url(r'^login/$',LoginView.as_view(),name = 'login'),
    url(r'^logout/$',LogoutView.as_view(),name = 'logout'),
    url(r'^$', ShowIndex.as_view()),
    url(r'^search/$', SearchView.as_view(),name='search'),
    url(r'^movies/', include('movie.urls',namespace='movie')),
    url(r'^booking/', include('booking.urls',namespace='booking')),
    url(r'^theatres/', include('theatre.urls',namespace='theatre')),
    url(r'^register/$',RegisterView.as_view(),name='register'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/booking/urls.py
# from django.conf.urls import url
from django.urls import re_path
from .views import payment_gateway, payment_confirmation, reserve_seat,BookingListView,BookingDetailView\
,BookingDeleteView
app_name = 'booking'
urlpatterns = [
   re_path(r'^seatchoice/(?P<show_id>\d+)/$', reserve_seat, name='reserve_seat'),
   re_path(r'^payment/$', payment_gateway, name='payment_gateway'),
   re_path(r'^payment_confirmation/$', payment_confirmation, name='payment_confirmation'),
   re_path(r'^$', BookingListView.as_view(), name='list'),
   re_path(r'^(?P<btid>.*)/delete/$', BookingDeleteView.as_view(), name='delete')
 ,  re_path(r'^(?P<btid>.*)/$', BookingDetailView.as_view(), name='detail'),
#   re_path(r'^(?P<btid>.*)/delete/$', BookingDeleteView.as_view(), name='delete')
]

backend/movie/urls.py
# from django.conf.urls import url
from django.urls import re_path
from .views import MovieListView, movie_details

app_name = 'movie'

urlpatterns = [
    
    re_path(r'^$', MovieListView.as_view(), name='list'),
    re_path(r'^(?P<movie_id>\d+)/$', movie_details, name='detail'),
        
]

backend/booking/models.py
from django.db import models
from django.contrib.auth import get_user_model
from theatre.models import Show
from django.urls import reverse
from django.db.models.signals import post_delete
User = get_user_model()
# Create your models here.


class Booking(models.Model):
    payment_choice = (
        ('Debit Card', 'Debit Card'),
        ('Credit Card', 'Credit Card'),
        ('Net Banking', 'Net Banking'),
        ('Wallet', 'Wallet'),
    )
    id                =     models.CharField(primary_key=True, max_length=200)
    timestamp         =     models.DateTimeField('%Y-%m-%d %H:%M:%S')
    payment_type      =     models.CharField(max_length=11, choices=payment_choice)
    paid_amount       =     models.DecimalField(max_digits=8, decimal_places=2)
    paid_by           =     models.ForeignKey(User, on_delete=models.DO_NOTHING)

    def __str__(self):
        return str(self.id)
    def get_absolute_url(self):
        return reverse('booking:detail',kwargs={'btid':self.id})
    
    #def get_absolute_url(self):

class Seat(models.Model):
    seat_choice = (
        ('', 'Select'),
        ('Silver', 'Silver'),
        ('Gold', 'Gold'),
        ('Platinum', 'Platinum'),
    )
    no              =       models.CharField(max_length=3)
    seat_type       =       models.CharField(max_length=8, choices=seat_choice, blank=False)
    show            =       models.ForeignKey(Show, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('no', 'show')

    def __str__(self):
        return self.no + str(self.show)


class BookedSeat(models.Model):
    seat            =       models.ForeignKey(Seat, on_delete=models.CASCADE)
    booking         =       models.ForeignKey(Booking, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('seat', 'booking')

    def __str__(self):
        return str(self.seat) + '|' + str(self.booking)


def delete_reverse(sender,instance,*args,**kwargs):
    try:
        if instance.seat:
            instance.seat.delete()
    except:
        pass

post_delete.connect(delete_reverse,sender=BookedSeat)

backend/booking/forms.py
from django import forms
from .models import Seat, Booking


class SeatForm(forms.ModelForm):

	class Meta:
		model = Seat
		fields = ('seat_type',)


class BookingForm(forms.ModelForm):

	class Meta:
		model = Booking
		fields = ('payment_type',)

backend/booking/views.py
from django.shortcuts import render, get_object_or_404
from .models import Booking, BookedSeat, Seat
from theatre.models import Show
from .forms import SeatForm, BookingForm
from django.urls import reverse_lazy
#from django.views.generic import CreateView
import datetime
from django.views.generic import ListView,DetailView,DeleteView
from theatre.models import Theatre
from django.shortcuts import redirect
from django.http.response import Http404

# Create your views here.

def reserve_seat(request, show_id):
    try:
        show_info = Show.objects.get(pk=show_id)
    except Theatre.DoesNotExist:
        raise Http404("Page does not exist")
    form = SeatForm()
    return render(request, 'reserve_seat.html', 
        {'show_info': show_info, 'form': form})


def payment_gateway(request):
    if request.POST:
        seats = request.POST.get('selected_seat')
        seat_type = request.POST.get('seat_type')
        show_id = request.POST.get('show_id')

        show = Show.objects.get(pk=show_id)
        seats = seats.split(',')
        book_seat = []
        for each in seats:
            if Seat.objects.filter(no=each, show=show).exists():
                return render(request, 'reserve_seat.html', 
                    {'show_info': show, 'form': SeatForm()})
            s = Seat(no=each, seat_type=seat_type, show=show)
            book_seat.append(s)
        Seat.objects.bulk_create(book_seat)

        form = BookingForm()

        price_dict = {'Platinum': 300, 'Gold': 200, 'Silver': 100}
        ticket_price = price_dict[seat_type]*len(book_seat)

        seat_str = ""
        for i in range(0, len(seats)):
            if i == len(seats)-1:
                seat_str += seats[i]
            else:
                seat_str += seats[i] + ','

        return render(request, 'payment_gateway.html', 
            {'seats': seat_str, 'seat_type': seat_type, 
            'show': show, 'form': form, 'ticket_price': ticket_price})
    else:
        return redirect('theatre.views.theatre_list')


def payment_confirmation(request):
    if request.POST:
        show_id = request.POST.get('show_id')
        show = Show.objects.get(pk=show_id)
        seats = request.POST.get('selected_seat')
        seats = seats.split(',')
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        payment_type = request.POST.get('payment_type')
        paid_amount = request.POST.get('amount')
        paid_by = request.user
        id = str(show) + "**" + str(seats) + "**" + timestamp
        book = Booking(id=id, timestamp=timestamp, payment_type=payment_type, 
            paid_amount=paid_amount, paid_by=paid_by)
        book.save()

        booked_seat = []

        for seat in seats:
            # print(seat)
            s = Seat.objects.get(no=seat, show=show)
            b = Booking.objects.get(pk=id)
            booked = BookedSeat(seat=s, booking=b)
            booked_seat.append(booked)

        BookedSeat.objects.bulk_create(booked_seat)

        return render(request, 'payment_confirmation.html')
    else:
        return redirect('theatre.views.theatre_list')


class BookingListView(ListView):
    def get_queryset(self):
        return Booking.objects.filter(paid_by=self.request.user)
    
class BookingDetailView(DetailView):
    def get_queryset(self):
        return Booking.objects.filter(paid_by=self.request.user)
    
    def get_object(self,*args,**kwargs):
        btid = self.kwargs.get('btid')
        obj = get_object_or_404(Booking,id=btid)
        return obj
    ### add function
    # def post(self, request, id=None, *args, **kwargs):
    #     context = {}
    #     obj = self.get_object()
    #     if obj is not None:
    #         context['object'] = obj
    #         print(context)
    #     return render(request, "booking_detail.html", context)


class BookingDeleteView(DeleteView):
    model = Booking
    success_url = reverse_lazy('booking:list')    
    def get_object(self,*args,**kwargs):
        btid = self.kwargs.get('btid')
        obj = get_object_or_404(Booking,id=btid)
        return obj

backend/booking/templates/payment_confirmation.html
{% extends "base.html" %}

{% block title %}
    BoxOffice | Payment
{% endblock %}

{% block content %}

	<h1>Payment Confirmation</h1>
	<hr /><br /><br /><br /><br />
	<p class="text-center text-success lead">Booking Done!</p>
	

{% endblock %}

backend/booking/templates/payment_gateway.html
{% extends "base.html" %}

{% block title %}
    BoxOffice | Payment
{% endblock %}

{% block content %}

	<h1>Payment</h1><hr />
	<div class="jumbotron" style="background-color:#add8e6">	
	<div class="booking">
		<form method="post" action="{% url 'booking:payment_confirmation' %}">
			{% csrf_token %}
			<input type="hidden" id="show_id" name="show_id" value="{{ show.id }}">
			<!--<pre>-->
			<div class="row">
			<div class="col-sm-offset-3 col-sm-1">
			<label>Movie:</label>
			</div>
			<div class="col-sm-4">
			<input id="movie" class="form form-control" name="movie" value="{{ show.movie }}" readonly><br /><br />
			</div>
			</div>
			<div class="row">
			<div class="col-sm-offset-3 col-sm-1">
            <label>Theatre:</label>
            </div>
            <div class="col-sm-4">
            <input id="theatre" class="form form-control" name="theatre" value="{{ show.theatre }}"  readonly><br /><br />
			</div>
			</div>
			<div class="row">
			<div class="col-sm-offset-3 col-sm-1">
            <label>Screen No:</label>
            </div>
            <div class="col-sm-4">
            <input id="screen" class="form form-control" name="screen" value="{{ show.screen }}"  readonly><br /><br />
			</div>
			</div>
			<div class="row">
            <div class="col-sm-offset-3 col-sm-1">
			<label>Showtime:</label>
			</div>
			<div class="col-sm-4">
			<input id="showtime" class="form form-control"  name="showtime" value="{{ show.time }}"  readonly><br /><br />
			</div>
			</div>
			<div class="row">
            <div class="col-sm-offset-3 col-sm-1">
            <label>Date:</label>
            </div>
            <div class="col-sm-4">
            <input id="date" class="form form-control" name="date" value="{{ show.date }}"  readonly><br /><br />
			</div>
			</div>
			<div class="row">
            <div class="col-sm-offset-3 col-sm-1">
			<label>Seats:</label>
			</div>
			<div class="col-sm-4">
			<input id="selected_seat" class="form form-control" name="selected_seat" value="{{ seats }}"  readonly><br /><br />
			</div>
			</div>
			<div class="row">
            <div class="col-sm-offset-3 col-sm-1">
			<label>Seat Type:</label>
			</div>
			<div class="col-sm-4">
			<input id="seat_type" class="form form-control" name="seat_type" value="{{ seat_type }}"  readonly><br /><br />
			</div>
			</div>
			<div class="row">
            <div class="col-sm-offset-3 col-sm-1">
            <label>Payable Amount:</label>
            </div>
            <div class="col-sm-4">
            <input id="amount" class="form form-control" name="amount" value="{{ ticket_price }}"  readonly><br /><br />
			</div>
			</div>
			<div class="row">
			<div class="col-sm-offset-5 col-sm-7">
			{{ form.as_p }}
			</div>
			</div>
			<div class="row">
            <div class="col-sm-offset-5 col-sm-7">
			<button class="btn btn-primary btn-lg" type="submit">Pay</button>
			</div>
			</div>
			<!--</pre>-->
		</form>
	</div>
	</div>

{% endblock %}

backend/booking/templates/reserve_seat.html
{% extends "base.html" %}

{% block title %}
BoxOffice | Reserve Seats
{% endblock %}

{% block content %}

	<h1>Select Seats</h1>
	<h2>{{ show_info }}</h2>
	<div class="seatDiv">
		<div class="seatArray">
		</div>
		<div class="seatForm">
			<form method="post" action="{% url 'booking:payment_gateway' %}">
				{% csrf_token %}
				{{ form.as_p }}
				Seats: <input name="selected_seat" id="selected_seat" type="text" readonly />
				<br /><br />
				<span>Total number of seats: </span><span id="no_of_seats">0</span>
				<input type="hidden" name="show_id" id="show_id" value="{{ show_info.id }}" readonly />
				<br /><br />
				<button type="submit" class="btn btn-warning">Confirm</button>
			</form>
		</div>
	</div>
	

{% endblock %}

backend/booking/templates/swagger-ui.html
   
<!DOCTYPE html>
<html>
  <head>
    <title>Swagger</title>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" href="//unpkg.com/swagger-ui-dist@3/swagger-ui.css" />
  </head>
  <body>
    <div id="swagger-ui"></div>
    <script src="//unpkg.com/swagger-ui-dist@3/swagger-ui-bundle.js"></script>
    <script>
    const ui = SwaggerUIBundle({
        url: "{% url schema_url %}",
        dom_id: '#swagger-ui',
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIBundle.SwaggerUIStandalonePreset
        ],
        layout: "BaseLayout",
        requestInterceptor: (request) => {
          request.headers['X-CSRFToken'] = "{{ csrf_token }}"
          return request;
        }
      })
    </script>
  </body>
</html>