backend/BoxOffice/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.contrib.auth.views import LoginView, LogoutView
from django.conf.urls.static import static
from django.conf.urls import url,include
from home.views import ShowIndex, RegisterView, LoginView,SearchView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/v1/', include('myapi.urls')),
    url(r'^login/$',LoginView.as_view(),name = 'login'),
    url(r'^logout/$',LogoutView.as_view(),name = 'logout'),
    url(r'^$', ShowIndex.as_view()),
    url(r'^search/$', SearchView.as_view(),name='search'),
    url(r'^movies/', include('movie.urls',namespace='movie')),
    url(r'^booking/', include('booking.urls',namespace='booking')),
    url(r'^theatres/', include('theatre.urls',namespace='theatre')),
    url(r'^register/$',RegisterView.as_view(),name='register'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

backend/booking/urls.py
# from django.conf.urls import url
from django.urls import re_path
from .views import payment_gateway, payment_confirmation, reserve_seat,BookingListView,BookingDetailView\
,BookingDeleteView
app_name = 'booking'
urlpatterns = [
   re_path(r'^seatchoice/(?P<show_id>\d+)/$', reserve_seat, name='reserve_seat'),
   re_path(r'^payment/$', payment_gateway, name='payment_gateway'),
   re_path(r'^payment_confirmation/$', payment_confirmation, name='payment_confirmation'),
   re_path(r'^$', BookingListView.as_view(), name='list'),
   re_path(r'^(?P<btid>.*)/delete/$', BookingDeleteView.as_view(), name='delete')
 ,  re_path(r'^(?P<btid>.*)/$', BookingDetailView.as_view(), name='detail'),
#   re_path(r'^(?P<btid>.*)/delete/$', BookingDeleteView.as_view(), name='delete')
]

backend/movie/urls.py
# from django.conf.urls import url
from django.urls import re_path
from .views import MovieListView, movie_details

app_name = 'movie'

urlpatterns = [
    
    re_path(r'^$', MovieListView.as_view(), name='list'),
    re_path(r'^(?P<movie_id>\d+)/$', movie_details, name='detail'),
        
]

backend/movie/models.py
from django.db import models
from django.db.models import Q
from django.urls.base import reverse
# Create your models here.
class MovieQuerySet(models.query.QuerySet):
    def search(self,query):
        lookup = (
            Q(name__icontains=query)|
            Q(director__icontains=query)|
            Q(language__icontains=query)|
            Q(cast__icontains=query)
        )
        return self.filter(lookup).distinct()

class MovieManager(models.Manager):
    def get_queryset(self):
        return MovieQuerySet(self.model,self._db)
    def search(self,query):
        return self.get_queryset().search(query)


class Movie(models.Model):
    lang_choice=(
            ('ENGLISH','English'),
            # ('BENGALI','Bengali'),
            # ('HINDI','Hindi'),
            # ('TAMIL','Tamil'),
            # ('TELUGU','Telugu'),
            # ('MALAYALAM','Malayalam'),
            # ('MARATHI','Marathi'),
            # ('FRENCH','French'),
            ('KOREAN', 'Korean'),
            ('RUSSIAN', 'Russian'),
            ('CHINESE','Chinese'),
        )
    rating_choice=(
            ('U','U'),
            ('UA','U/A'),
            ('A','A'),
            ('R','R'),
        )    
    name              =     models.CharField(max_length=50)
    cast              =     models.CharField(max_length=100)
    director          =     models.CharField(max_length=20)
    language          =     models.CharField(max_length=10,choices=lang_choice, blank=True)
    run_length        =     models.IntegerField(help_text='Enter run length in minutes', blank=True)
    certificate       =     models.CharField(max_length=2,choices=rating_choice, blank=True)
    popularity_index  =     models.IntegerField(unique=True,null=True)
    trailer           =     models.CharField(max_length=200, default="youtube.com")    
    image             =     models.ImageField(null=True)
    
    objects = MovieManager()

    def get_absolute_url(self):
        return reverse('movie:detail',kwargs={'movie_id':self.pk})
    
    def __str__(self):
        return self.name

backend/theatre/models.py
from django.db import models
import datetime

# Create your models here.
from django.contrib.auth import get_user_model
from movie.models import Movie
from django.urls.base import reverse
User = get_user_model()

class Theatre(models.Model):
    city_choice=(
        # ('DELHI','Delhi'),
        # ('KOLKATA','Kolkata'),
        # ('MUMBAI','Mumbai'),
        # ('CHENNAI','Chennai'),
        # ('BANGALORE','Bangalore'),
        # ('HYDERABAD','Hyderabad')
        ('MOSCOW','Moscow'),
        ('STPETERSBURG', 'StPetersBurg'),
    )
    name            =   models.CharField(max_length=50,null=False)
    city            =   models.CharField(max_length=20,choices=city_choice,null=False)
    address         =   models.CharField(max_length=30)
    no_of_screen    =   models.IntegerField()
    admin_id        =   models.ForeignKey(User,on_delete=models.CASCADE)
    
    def __str__(self):
        return self.name+"**"+self.address+"**"+self.city
    
    def get_absolute_url(self):
        return reverse('theatre:detail',kwargs={'theatre_id':self.pk})
    
class Show(models.Model):
    movie       =    models.ForeignKey(Movie,on_delete=models.CASCADE)
    theatre     =    models.ForeignKey(Theatre,on_delete=models.CASCADE)
    screen      =    models.IntegerField()
    date        =    models.DateField(default=datetime.date.today)
    time        =    models.TimeField(default=datetime.datetime.now())
    
    def __str__(self):
        return str(self.movie)+"**"+str(self.theatre)+"**"+str(self.date)+"**"+str(self.time)
    

backend/movie/views.py
from django.shortcuts import render
from .models import Movie
from theatre.models import Show
from django.views.generic import ListView 
# Create your views here.
from django.shortcuts import Http404
import datetime

class MovieListView(ListView):
    def get_queryset(self):
        return Movie.objects.all().order_by('language')
       
       
    def get_context_data(self,*args, **kwargs):
        context = super(MovieListView,self).get_context_data(*args,**kwargs)
        movies = Movie.objects.all().order_by('language')
        movie_list = []
        movie_by_lang = []
        lang = movies[0].language
        for i in range(0, len(movies)):
            if lang != movies[i].language:
                lang = movies[i].language
                movie_list.append(movie_by_lang)
                movie_by_lang = []
            movie_by_lang.append(movies[i])
        movie_list.append(movie_by_lang)
        context['movie_list'] = movie_list
        return context


def movie_details(request, movie_id):
    try:
        movie_info = Movie.objects.get(pk=movie_id)
        shows = Show.objects.filter(movie=movie_id, 
            date=datetime.date.today()).order_by('theatre')
        show_list = []

        if shows:
            show_by_theatre = []
            theatre = shows[0].theatre
            for i in range(0, len(shows)):
                if theatre != shows[i].theatre:
                    theatre = shows[i].theatre
                    show_list.append(show_by_theatre)
                    show_by_theatre = []
                show_by_theatre.append(shows[i])
    
            show_list.append(show_by_theatre)

    except Movie.DoesNotExist:
        raise Http404("Page does not exist")
    return render(request, 'movie/movie_detail.html', 
        {'movie_info': movie_info, 'show_list': show_list})
      
    
    
    

backend/movie/templates/movie/movie_detail.html
{% extends "base.html" %}

{% block title %}
BoxOffice | Movie Details
{% endblock %}

{% block content %}


<div class="media">
  <div class="media-left">
    <a href="#">
      <img class="media-object" src="{{ movie_info.image.url }}" alt="{{ movie_info.name }}">
    </a>
    <a href="#" style="margin:15px;" onclick="watchTrailer('{{ movie_info.name }}','{{ movie_info.trailer }}')" role="button" class="btn btn-primary btn-sm">Watch Trailer</a>
  </div>
  <div class="media-body form-horizontal">
    <h4 class="media-heading">{{ movie_info.name }}</h4>
    <div class="form-group">
      <label class="col-sm-2 control-label">Cast</label>
      <div class="col-sm-10">
        <p class="form-control-static">{{ movie_info.cast }}</p>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Director</label>
      <div class="col-sm-10">
        <p class="form-control-static">{{ movie_info.director }}</p>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Language</label>
      <div class="col-sm-10">
        <p class="form-control-static">{{ movie_info.language }}</p>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Runtime</label>
      <div class="col-sm-10">
        <p class="form-control-static">{{ movie_info.run_length }} mins</p>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label">Certificate</label>
      <div class="col-sm-10">
        <p class="form-control-static">{{ movie_info.certificate }}</p>
      </div>
    </div>
  </div>
</div>

<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Now Showing</h3>
  </div>
  <div class="panel-body">
        {% if show_list %}
        {% for theatre in show_list %}
        <div class="media">
          
          <div class="media-body">
            <h4 class="media-heading"><a href="{{ theatre.get_absolute_url }}">{{ theatre.0.theatre.name }} | {{ theatre.0.theatre.address }}</a></h4>
          <ul>
            {% for showtime in theatre %}
              <li>{% if user.is_authenticated %}<a href="{% url 'booking:reserve_seat' showtime.id %}">{{ showtime.time|time:"h:i A" }}</a>{% else %}<p>{{ showtime.time|time:"h:i A" }}</p>{% endif %}</li>
            {% endfor %}
            </ul> 
          </div>
        </div>
        {% endfor %}
        {% else %}
        <p class="lead">No Shows</p>
        {% endif %}
  </div>
</div>

{% endblock %}

backend/movie/templates/movie/movie_list.html
{% extends "base.html" %}

{% block title %}
    BoxOffice | Theatres
{% endblock %}

{% block content %}
<div class="jumbotron">
    {% for category in movie_list %}
    
    
        <div class="text-center">
            <h2>{{ category.0.language }} MOVIES</h2>
        </div>
        <div class="row">
        {% for movie in category %}
            <div class="col-sm-4">
                <div class="thumbnail">
                    <img src="{{ movie.image.url }}" alt="{{ movie.name }}">
                    <div class="caption">
                        <h3><a href="{% url 'movie:detail' movie.id %}">{{ movie.name }}</a></h3>
                        <p>{{ movie.cast }}</p>
                        <p>{{ movie.language }} | {{ movie.certificate }}</p>
                        <p><a class="btn btn-default" onclick="watchTrailer('{{ movie.name }}','{{ movie.trailer }}')" role="button">Watch Trailer</a>{% if user.is_authenticated %} <a class="btn btn-primary" href="{% url 'movie:detail' movie.id %}" role="button">Book Now</a>{% endif %}</p>
                     </div>
                </div>
            </div>
        {% if forloop.counter|divisibleby:3 or forloop.counter == category|length %}
        </div>
        {% endif %}
        {% if forloop.counter != category|length %}
        <div class="row">
        
        {% endif %}
        {% endfor %}
    </div>  
      
    {% endfor %}
</div>
{% endblock %}